#SPDX-License-Identifier: MIT-0
---
- name: Update packages
  ansible.builtin.apt:
    update_cache: yes  

- name: "Role for install all required packages"
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop: "{{ packages }}"

